language: node_js
node_js: "10"

addons:
  apt:
    packages:
      - realpath
      - xvfb

install:
  - npm install -g elm@0.19.0
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
